version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PortfolioBackendSAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-duy0ii4a2aj5"
s3_prefix = "PortfolioBackendSAM"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
